[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio", "time"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "signal"] }
serenity = "0.12"
slug = "0.1.6"
